#ifndef VMCODES_H
#define VMCODES_H


#include "../../included/Macro.h"

#define VMECSHIFT 24

#define VM_ERRCODE(ec)  BUILD_ERRCODE (ec, VMECSHIFT)

typedef enum
{
    VM_FOPENERR,
    VM_FREADERR,
    VM_ALLOCATIONERR,
    VM_NULLRECEIVED,
    
    VM_REGMISSADDRESSING,
    VM_CODESEGVERIFICATION,
    VM_RAMVERIFICATION,
    VM_STACKVERIFICATION,
    VM_ERRONINIT,
    VM_VMSELFTESTING,

    VM_WRONGVERSION,
    VM_OPCODENOTFOUND,
    VM_MISSINGOPERAND,
    VM_BYTECODECORRUPTED,

    VM_RUNTIMEERR,
    VM_DIVISIONBYZERO,
    VM_SEGFAULT,

    VM_UNKNOWNERR,
}VMEC;


#endif