#ifndef TRANSLATORCODES_H
#define TRANSLATORCODES_H


#include "../../included/Macro.h"

#define TRNSLTEC_SHIFT 16

#define TRNSLT_ERRCODE(ec)  BUILD_ERRCODE (ec, TRNSLTEC_SHIFT)

typedef enum
{
    TRNSLTR_INTERNALERROR,
    TRNSLTR_FOPENERR,
    TRNSLTR_NULLRECEIVED,
    TRNSLTR_SYNTAX,
    TRNSLTR_WRITINGERROR,
    TRNSLTR_BUFOVERFLOW,
}TrnsltrEC;


#endif